// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nutrition.Api.Data;

#nullable disable

namespace Nutrition.Api.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutrition.Api.Data.AcceptedPlan", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CheckInWeekday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("CoachingSettingsRevision")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProfileRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Nutrition.Api.Data.AiUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Requests")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Date");

                    b.ToTable("Usage");
                });

            modelBuilder.Entity("Nutrition.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CheckInWeekday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateOnly?>("CoachingSettingsChangedDate")
                        .HasColumnType("date");

                    b.Property<long>("CoachingSettingsRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("EnergyUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProfileRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<long>("TrajectoryRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MissingDayAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ask");

                    b.Property<string>("WeightGoalMetric")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("scale");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slot")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nutrition.Api.Data.BodyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreationOrder")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PendingPhotosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeightContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "CreationOrder")
                        .IsUnique();

                    b.HasIndex("UserId", "Deleted", "Date", "CreationOrder");

                    b.ToTable("BodyRecords");
                });

            modelBuilder.Entity("Nutrition.Api.Data.CheckInDecision", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CheckInWeekday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("InputRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "WeekStart");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("Nutrition.Api.Data.DailyExpenditureEstimate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("EffectiveGoal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Expenditure")
                        .HasColumnType("double precision");

                    b.Property<double>("Gain")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalRatePercent")
                        .HasColumnType("double precision");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text");

                    b.Property<double?>("Observed")
                        .HasColumnType("double precision");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int?>("SuggestedCalories")
                        .HasColumnType("integer");

                    b.Property<double?>("TrendWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "Date");

                    b.HasIndex("UserId", "Date");

                    b.HasIndex("UserId", "SourceRevision");

                    b.ToTable("DailyExpenditureEstimates", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyExpenditureEstimates_Confidence", "\"Confidence\" >= 0 AND \"Confidence\" <= 1");

                            t.HasCheckConstraint("CK_DailyExpenditureEstimates_Expenditure", "\"Expenditure\" IS NULL OR \"Expenditure\" >= 0");

                            t.HasCheckConstraint("CK_DailyExpenditureEstimates_SuggestedCalories", "\"SuggestedCalories\" IS NULL OR \"SuggestedCalories\" >= 0");
                        });
                });

            modelBuilder.Entity("Nutrition.Api.Data.DayStatus", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Nutrition.Api.Data.DiaryEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PortionGrams")
                        .HasColumnType("double precision");

                    b.Property<string>("PortionLabel")
                        .HasColumnType("text");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Nutrition.Api.Data.Food", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("CookedYieldGrams")
                        .HasColumnType("double precision");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<bool>("Favourite")
                        .HasColumnType("boolean");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<double>("ServingGrams")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Nutrition.Api.Data.MutationReceipt", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Created");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Nutrition.Api.Data.PhaseDecision", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ProfileRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ReachedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProfileRevision")
                        .IsUnique();

                    b.ToTable("PhaseDecisions");
                });

            modelBuilder.Entity("Nutrition.Api.Data.PhysiquePhoto", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Angle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bytes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Date");

                    b.HasIndex("UserId", "SetId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Nutrition.Api.Data.ScanJob", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("ImageBytes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectPath")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Created");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("Nutrition.Api.Data.Session", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Hash");

                    b.HasIndex("Expires");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Nutrition.Api.Data.Weight", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Kg")
                        .HasColumnType("double precision");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("Nutrition.Api.Data.AcceptedPlan", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.AiUsage", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.BodyRecord", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nutrition.Api.Data.BodyMeasurements", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("BodyRecordUserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BodyRecordId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("BodyFatPercent")
                                .HasColumnType("double precision")
                                .HasColumnName("BodyFatPercent");

                            b1.Property<double?>("ChestCm")
                                .HasColumnType("double precision")
                                .HasColumnName("ChestCm");

                            b1.Property<double?>("HipsCm")
                                .HasColumnType("double precision")
                                .HasColumnName("HipsCm");

                            b1.Property<double?>("LeftBicepsCm")
                                .HasColumnType("double precision")
                                .HasColumnName("LeftBicepsCm");

                            b1.Property<double?>("LeftCalfCm")
                                .HasColumnType("double precision")
                                .HasColumnName("LeftCalfCm");

                            b1.Property<double?>("LeftForearmCm")
                                .HasColumnType("double precision")
                                .HasColumnName("LeftForearmCm");

                            b1.Property<double?>("LeftThighCm")
                                .HasColumnType("double precision")
                                .HasColumnName("LeftThighCm");

                            b1.Property<double?>("NeckCm")
                                .HasColumnType("double precision")
                                .HasColumnName("NeckCm");

                            b1.Property<double?>("RightBicepsCm")
                                .HasColumnType("double precision")
                                .HasColumnName("RightBicepsCm");

                            b1.Property<double?>("RightCalfCm")
                                .HasColumnType("double precision")
                                .HasColumnName("RightCalfCm");

                            b1.Property<double?>("RightForearmCm")
                                .HasColumnType("double precision")
                                .HasColumnName("RightForearmCm");

                            b1.Property<double?>("RightThighCm")
                                .HasColumnType("double precision")
                                .HasColumnName("RightThighCm");

                            b1.Property<double?>("ShouldersCm")
                                .HasColumnType("double precision")
                                .HasColumnName("ShouldersCm");

                            b1.Property<double?>("WaistCm")
                                .HasColumnType("double precision")
                                .HasColumnName("WaistCm");

                            b1.HasKey("BodyRecordUserId", "BodyRecordId");

                            b1.ToTable("BodyRecords");

                            b1.WithOwner()
                                .HasForeignKey("BodyRecordUserId", "BodyRecordId");
                        });

                    b.Navigation("Measurements")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.CheckInDecision", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.DailyExpenditureEstimate", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.DayStatus", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.DiaryEntry", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.Food", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.MutationReceipt", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.PhaseDecision", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.PhysiquePhoto", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.ScanJob", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.Session", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrition.Api.Data.Weight", b =>
                {
                    b.HasOne("Nutrition.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
