using System.IO.Compression;
using System.Text.Json;

namespace Nutrition.Api.Services.FoodLookup;

/// <summary>
/// USDA FoodData Central generic foods (Foundation, SR Legacy, FNDDS), generated by
/// tools/usda-import and embedded in the API. Loaded once; searching it never leaves the process.
/// </summary>
public sealed class UsdaGenericDataset
{
    public const string ResourceName="usda-generic.json.gz";

    public sealed record Entry(FoodResult Result,string[] Stems,int LeadSegmentLength);

    private UsdaGenericDataset(IReadOnlyList<Entry> entries,IReadOnlyDictionary<string,string> releases)
    {
        Entries=entries;
        Releases=releases;
    }

    public IReadOnlyList<Entry> Entries { get; }
    /// <summary>FDC release per data type, recorded by the generator.</summary>
    public IReadOnlyDictionary<string,string> Releases { get; }
    public int Count=>Entries.Count;

    /// <summary>The dataset compiled into this assembly, or null when a build left it out.</summary>
    public static UsdaGenericDataset? Embedded()
    {
        using var stream=typeof(UsdaGenericDataset).Assembly.GetManifestResourceStream(ResourceName);
        return stream is null?null:Load(stream);
    }

    public static UsdaGenericDataset Load(Stream gzip)
    {
        using var inflated=new GZipStream(gzip,CompressionMode.Decompress);
        using var json=JsonDocument.Parse(inflated);
        var releases=new Dictionary<string,string>(StringComparer.Ordinal);
        if(json.RootElement.TryGetProperty("releases",out var list)&&list.ValueKind==JsonValueKind.Object)
            foreach(var release in list.EnumerateObject())releases[release.Name]=release.Value.GetString()??"";
        var entries=new List<Entry>();
        foreach(var food in json.RootElement.GetProperty("foods").EnumerateArray())
            if(Read(food) is { } entry)entries.Add(entry);
        return new UsdaGenericDataset(entries,releases);
    }

    private static Entry? Read(JsonElement food)
    {
        var name=FoodResults.Text(food,"n");
        if(name is null||FoodResults.Number(food,"k") is not { } calories)return null;
        var portions=new List<FoodPortion>();
        if(food.TryGetProperty("s",out var servings)&&servings.ValueKind==JsonValueKind.Array)
            foreach(var serving in servings.EnumerateArray())
                if(serving.ValueKind==JsonValueKind.Array&&serving.GetArrayLength()==2&&serving[0].GetString() is { } label&&FoodResults.TryNumber(serving[1],out var grams))
                    portions.Add(new FoodPortion(label,grams));
        var limited=FoodResults.LimitPortions(portions);
        var result=new FoodResult(name,calories,FoodResults.Number(food,"p"),FoodResults.Number(food,"f"),FoodResults.Number(food,"c"),FoodResults.Number(food,"fi"),
            UsdaGenericProvider.Attribution,100,limited,null,FoodResults.ServingCalories(calories,limited),"per100g",IsGeneric:true);
        return new Entry(result,FoodRanking.Stems(name),FoodRanking.Stems(name.Split(',')[0]).Length);
    }
}
