import '@fontsource-variable/inter/index.css';
import {createRoot} from 'react-dom/client';
import {registerAppServiceWorker} from './lib/registerAppServiceWorker';
import {initializeNativeApp,isNativeApp} from './lib/nativeApp';
import {watchVirtualKeyboard} from './lib/virtualKeyboard';
import App from './App';
import {MobilePwaProvider} from './components/ui/MobilePwa';
import {activeTheme,applyTheme} from './lib/theme';
import './index.css';
import './touch.css';
import './logging.css';
import './check-in.css';
import './progress.css';
import './barcode.css';
import './accessibility.css';
import {measurePerformance} from './lib/performance';
const startupFinished=measurePerformance('startup.usable');
void registerAppServiceWorker().catch(()=>{});
void initializeNativeApp().catch(()=>{});
if(!isNativeApp())watchVirtualKeyboard();
applyTheme(activeTheme());
createRoot(document.getElementById('root')!).render(<MobilePwaProvider><App onUsable={startupFinished}/></MobilePwaProvider>);
