import {useEffect,useState} from 'react';
import {ArrowRight,Sprout} from 'lucide-react';
import {api} from '../lib/api';
import {Button} from './ui/Button';
import {Field} from './ui/Field';
export function Auth({onLogin}:{onLogin:(id:string)=>void}){
  const [register,setRegister]=useState(false);const [open,setOpen]=useState(false);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<{registrationOpen:boolean}>('/auth/status').then(s=>setOpen(s.registrationOpen)).catch(()=>setError('Connect to the service to sign in.'));},[]);
  return <main className="auth-layout"><section className="auth-story"><div className="brand"><Sprout/> nourish<span className="brand-dot">•</span></div><p className="eyebrow">A LITTLE MORE UNDERSTANDING, EVERY DAY</p><h1>Nutrition that<br/>learns with you.</h1><p>A simple food diary. A clearer picture of your needs.<br/>Small, thoughtful adjustments along the way.</p><div className="auth-foot">Your food. Your pace. Your private space.</div></section><section className="auth-panel"><h2>{register?'Make yourself at home':'Welcome back'}</h2><p>{register?'This private app has room for two accounts.':'Sign in to your nutrition diary.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const user=await api<{id:string}>('/auth/'+(register?'register':'login'),{username,password});localStorage.setItem('nourish-account',user.id);onLogin(user.id);}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}}}><Field label="Username" autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/><Field label="Password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:undefined} required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error" role="alert">{error}</p>}<Button variant="primary" disabled={busy} type="submit">{busy?'Connecting…':register?'Create account':'Sign in'}<ArrowRight size={18}/></Button></form>{open&&<Button variant="tertiary" onClick={()=>setRegister(!register)}>{register?'Already have an account? Sign in':'New here? Create an account'}</Button>}<small>Local unsynced work is kept on this device when you sign out.</small></section></main>;
}
