import {useEffect,useRef,useState} from 'react';
import {Camera,Search,ScanBarcode,Sparkles,Plus,Star} from 'lucide-react';
import type {Nourish} from '../useNourish';
import type {Entry,Food,Nutrients,ScanDraft} from '../types';
import {blankNutrients} from '../types';
import {api} from '../lib/api';
import {prepareImage} from '../lib/image';
import {number} from '../lib/format';
import {Button} from './ui/Button';
import {Field,SelectField} from './ui/Field';
import {FoodEditor,type FoodDraft} from './FoodEditor';
import {RecipeEditor} from './RecipeEditor';
import {ScanReview} from './ScanReview';
type SearchResult=Nutrients&{servingGrams:number};
export function LogFood({store,date,editing,onDone,initialAi=false}:{initialAi?:boolean;store:Nourish;date:string;editing:Entry|undefined;onDone:()=>void}){
  const [tab,setTab]=useState(initialAi?'ai':'saved');const [query,setQuery]=useState('');const [results,setResults]=useState<SearchResult[]>([]);const [draft,setDraft]=useState<Partial<Entry>|undefined>(editing);const [saveFood,setSaveFood]=useState<Food|true|false>(false);const [recipe,setRecipe]=useState(false);
  const [description,setDescription]=useState('');const [mode,setMode]=useState<ScanDraft['mode']>('description');const [photo,setPhoto]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [camera,setCamera]=useState(false);const video=useRef<HTMLVideoElement>(null);
  useEffect(()=>{
    if(!camera||!video.current)return;
    let stop:(()=>void)|undefined;let cancelled=false;
    void import('@zxing/browser').then(async({BrowserMultiFormatReader})=>{const reader=new BrowserMultiFormatReader();const controls=await reader.decodeFromVideoDevice(undefined,video.current!,result=>{if(result){setQuery(result.getText());setCamera(false);}});if(cancelled)controls.stop();else stop=()=>controls.stop();}).catch(()=>{setError('Camera unavailable. Enter the barcode digits or scan the nutrition label.');setCamera(false);});
    return()=>{cancelled=true;stop?.();};
  },[camera]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}};
  const log=async(data:FoodDraft)=>{
    if(saveFood){await store.mutate({kind:'food',recordId:saveFood===true?crypto.randomUUID():saveFood.id,expectedRevision:saveFood===true?0:saveFood.revision,delete:false,data:{...data,servingGrams:100,favourite:saveFood===true?true:saveFood.favourite,ingredientsJson:saveFood===true?'[]':saveFood.ingredientsJson,cookedYieldGrams:saveFood===true?null:saveFood.cookedYieldGrams}});setSaveFood(false);}
    else {await store.mutate({kind:'entry',recordId:editing?.id??crypto.randomUUID(),expectedRevision:editing?.revision??0,delete:false,data:{...data,date}});onDone();}
  };
  const choose=(food:SearchResult)=>{setSaveFood(false);setDraft({...food,quantity:100,unit:'g'});};
  const foods=store.state!.foods.filter(f=>!f.deleted&&f.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.favourite)-Number(a.favourite));
  if(date<(store.state!.detailCutoff??'2000-01-01'))return <section className="panel"><h1>This day is kept as a summary</h1><p>Detailed meal logging is available for the latest {store.state!.detailDays??7} days. Choose a recent date in Today to add food.</p><Button onClick={onDone}>Back to diary</Button></section>;
  return <><header className="page-heading"><div><h1>Log food</h1><p>{date}</p></div><Button onClick={()=>{setSaveFood(false);setDraft({...blankNutrients});}}><Plus size={18}/>Quick entry</Button></header>
  {draft&&<FoodEditor key={JSON.stringify(draft)} initial={draft} title={saveFood?'Save food · nutrition per 100 g':editing?'Edit food entry':'Review your food'} onSave={log} onClose={()=>{setDraft(undefined);setSaveFood(false);if(editing)onDone();}}/>}
  {recipe&&<RecipeEditor store={store} onClose={()=>setRecipe(false)}/>}
  <div className="tabs" role="group" aria-label="Food logging method">{[['saved','Your foods',Star],['search','Search',Search],['barcode','Barcode',ScanBarcode],['ai','AI logging',Sparkles]].map(([key,label,Icon])=><Button key={key as string} variant={tab===key?'primary':'secondary'} onClick={()=>setTab(key as string)}>{typeof Icon!=='string'&&<Icon size={17}/>}{label as string}</Button>)}</div>
  <section className="panel">
  {tab==='saved'&&<><div className="section-heading"><h2>Saved foods</h2><div className="actions"><Button onClick={()=>{setSaveFood(true);setDraft({...blankNutrients,quantity:100,unit:'g'});}}>Custom food</Button><Button onClick={()=>setRecipe(true)}>New recipe</Button></div></div><Field label="Find your food" placeholder="Rice, nasi lemak, kopi…" value={query} onChange={e=>setQuery(e.target.value)}/>{foods.length===0&&<p className="empty">Save your usual foods here. Search an ingredient, scan a label, or make your own recipe.</p>}{foods.map(food=><div className="food-row" key={food.id}><div className="food-description"><Button variant="tertiary" onClick={()=>choose(food)}>{food.name}</Button><small>{number(food.calories)} kcal / 100 g · {food.source}</small></div><Button variant="tertiary" aria-label={`${food.favourite?'Unfavourite':'Favourite'} ${food.name}`} onClick={()=>void run(()=>store.mutate({kind:'food',recordId:food.id,expectedRevision:food.revision,delete:false,data:{...food,favourite:!food.favourite}}))}><Star size={18} fill={food.favourite?'currentColor':'none'}/></Button><Button onClick={()=>{setSaveFood(food);setDraft({...food,quantity:100,unit:'g'});}}>Edit</Button></div>)}<h3>Recent diary foods</h3><div className="actions">{store.state!.entries.filter(e=>!e.deleted).slice(-8).reverse().map(e=><Button key={e.id} onClick={()=>{setSaveFood(false);setDraft({...e,id:undefined});}}>{e.name}</Button>)}</div></>}
  {(tab==='search'||tab==='barcode')&&<><h2>{tab==='barcode'?'Find a packaged food':'Search ingredients'}</h2><p>{tab==='barcode'?'Open Food Facts community data. Confirm the result against your package.':'USDA ingredient data. Malaysian mixed dishes are often better logged as a recipe or reviewed estimate.'}</p><form onSubmit={e=>{e.preventDefault();void run(async()=>setResults(tab==='barcode'?[await api<SearchResult>('/foods/barcode/'+encodeURIComponent(query))]:await api<SearchResult[]>('/foods/search?q='+encodeURIComponent(query))));}}><div className="search-line"><Field label={tab==='barcode'?'Barcode digits':'Search term'} required value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="primary" type="submit" disabled={busy}>{busy?'Searching…':'Search'}</Button></div></form>{tab==='barcode'&&<><Button onClick={()=>setCamera(!camera)}><Camera size={18}/>{camera?'Stop camera':'Scan barcode with camera'}</Button>{camera&&<video ref={video} className="camera-preview" muted playsInline autoPlay/>}</>}{results.map((result,i)=><div className="food-row" key={i}><div className="food-description"><strong>{result.name}</strong><small>{number(result.calories)} kcal / 100 g · {result.source}</small></div><Button onClick={()=>choose(result)}>Use</Button><Button onClick={()=>{setSaveFood(true);setDraft({...result,quantity:100,unit:'g'});}}>Save food</Button></div>)}</>}
  {tab==='ai'&&<><h2>AI food logging</h2><p>Describe a meal, take a photo, or scan a nutrition label. You review every estimate before it enters your diary.</p><SelectField disabled={busy} label="How would you like to log?" value={mode} onChange={v=>{setMode(v as ScanDraft['mode']);setPhoto(null);}}><option value="description">Describe my meal</option><option value="photo">Meal photo</option><option value="label">Nutrition label</option></SelectField><label className="field"><span>Meal description and portion details</span><textarea maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Nasi lemak: 150 g coconut rice, one egg, a little sambal, cucumber, peanuts and anchovies…"/></label>{mode!=='description'&&<Field key={mode} disabled={busy} label={mode==='label'?'Photograph the nutrition label':'Photograph your food'} type="file" accept="image/*" capture="environment" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file){setPhoto(null);void run(async()=>setPhoto(await prepareImage(file)));}}}/>}{photo&&mode!=='description'&&<p className="notice">Photo prepared without location metadata. It will be deleted after processing.</p>}<Button variant="primary" disabled={busy||(mode==='description'?!description.trim():!photo)} onClick={()=>void run(async()=>{await store.addScan({id:crypto.randomUUID(),mode,description,imageBase64:mode==='description'?null:photo});setDescription('');setPhoto(null);})}><Sparkles size={18}/>{mode==='label'?'Read nutrition label':'Estimate my meal'}</Button></>}
  {error&&<p className="error" role="alert">{error}</p>}</section>
  {store.local!.scans.map(scan=>scan.result?<ScanReview key={scan.id} scan={scan} store={store} date={date}/>:<section className="panel" key={scan.id}><h3>{scan.error?'Scan needs attention':'Your scan is saved on this device'}</h3><p>{scan.error??'Processing when connected. You can leave this screen; foreground reopening resumes the scan.'}</p><p>{scan.description}</p><div className="actions">{scan.error&&<Button onClick={()=>void run(()=>store.retryScan(scan.id))}>Retry draft</Button>}<Button onClick={()=>void store.removeScan(scan.id)}>Discard local draft</Button></div></section>)}
  </>;
}
