import {useEffect,useState} from 'react';
import type {Nourish} from '../useNourish';
import {api} from '../lib/api';
import {prepareImage} from '../lib/image';
import {today,number} from '../lib/format';
import {Button} from './ui/Button';
import {Field,SelectField} from './ui/Field';
type Photo={id:string;date:string;caption:string;angle:string;bytes:number};
type Gallery={configured:boolean;usedBytes:number;maxBytes:number;photos:Photo[]};
export function PhysiquePhotos({store}:{store:Nourish}){
  const [gallery,setGallery]=useState<Gallery>();const [date,setDate]=useState(today());const [caption,setCaption]=useState('');const [angle,setAngle]=useState('front');const [image,setImage]=useState<string>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [skip,setSkip]=useState(0);const [selected,setSelected]=useState<Photo[]>([]);const [deleting,setDeleting]=useState<string>();
  const drafts=store.local!.photoDrafts??[];
  useEffect(()=>{void api<Gallery>('/photos?skip='+skip).then(setGallery).catch(ex=>setError(ex.message));},[skip,drafts.length]);
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}};
  return <section className="panel physique"><div className="section-heading"><div><h2>Physique progress</h2><p>Private photos, consistent lighting, a longer perspective.</p></div></div><p className="notice">Your progress photos are private. They stay in your history until you delete them.</p>{gallery&&!gallery.configured&&<p>Google Cloud photo storage needs configuration. You can prepare a local draft now.</p>}
    <form onSubmit={e=>{e.preventDefault();if(image)void action(async()=>{await store.addPhoto({id:crypto.randomUUID(),date,caption,angle,imageBase64:image});setImage(undefined);setCaption('');});}}><div className="form-grid"><Field label="Photo date" type="date" max={today()} required value={date} onChange={e=>setDate(e.target.value)}/><SelectField label="Photo angle" value={angle} onChange={setAngle}><option value="front">Front</option><option value="side">Side</option><option value="back">Back</option><option value="other">Other</option></SelectField></div><Field label="Photo caption (optional)" maxLength={160} value={caption} onChange={e=>setCaption(e.target.value)}/><Field label="Choose physique photo" type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void action(async()=>setImage(await prepareImage(file,750000)));}}/>{image&&<><img className="photo-preview" src={'data:image/jpeg;base64,'+image} alt="Your selected physique photo"/><p>Compressed to {number(image.length*.75/1000)} KB, up to 1600 px, without original location metadata.</p></>}<Button type="submit" variant="primary" disabled={!image||busy}>{busy?'Preparing…':'Save photo draft and upload'}</Button></form>
    {drafts.map(d=><div className="notice" key={d.id}><p>{d.date} · {d.angle} · {d.error??'Saved locally; uploading when connected.'}</p><div className="actions">{d.error&&<Button onClick={()=>void store.retryPhoto(d.id)}>Retry photo</Button>}<Button onClick={()=>void store.removePhotoDraft(d.id)}>Discard local photo draft</Button></div></div>)}
    {gallery&&<><p className="source">Photo storage: {number(gallery.usedBytes/1048576,1)} / {number(gallery.maxBytes/1048576)} MiB. This budget is configurable.</p><h3>Compare your progress</h3><p>Select two photos. Choosing a similar angle and lighting makes comparisons more useful.</p>{selected.length>0&&<div className="photo-comparison">{selected.map(p=><figure key={p.id}><img src={`/api/photos/${p.id}/content`} alt={`${p.angle} physique photo from ${p.date}`}/><figcaption>{p.date} · {p.angle}<Button variant="tertiary" onClick={()=>setSelected(selected.filter(s=>s.id!==p.id))}>Remove from comparison</Button></figcaption></figure>)}</div>}<div className="photo-gallery">{gallery.photos.map(p=><figure key={p.id}><img src={`/api/photos/${p.id}/content`} alt={`${p.angle} physique photo from ${p.date}`} loading="lazy"/><figcaption><strong>{p.date}</strong><p>{p.angle} · {p.caption}</p><div className="actions"><Button disabled={selected.some(s=>s.id===p.id)} onClick={()=>setSelected([...selected.slice(-1),p])}>Compare</Button><Button variant="tertiary" onClick={()=>setDeleting(p.id)}>Delete</Button></div>{deleting===p.id&&<div className="notice"><p>Delete this photo from your progress history? It won’t be available in the app afterward.</p><Button variant="destructive" disabled={busy} onClick={()=>void action(async()=>{await api(`/photos/${p.id}/delete`,{});setSelected(selected.filter(s=>s.id!==p.id));setGallery(await api<Gallery>('/photos?skip='+skip));setDeleting(undefined);})}>Delete photo</Button><Button onClick={()=>setDeleting(undefined)}>Keep photo</Button></div>}</figcaption></figure>)}</div><div className="actions"><Button disabled={skip===0} onClick={()=>setSkip(Math.max(0,skip-24))}>Newer photos</Button><Button disabled={gallery.photos.length<24} onClick={()=>setSkip(skip+24)}>Older photos</Button></div></>}{error&&<p className="error" role="alert">{error}</p>}
  </section>;
}

