import {useState} from 'react';
import type {Food} from '../types';
import type {Nourish} from '../useNourish';
import {Button} from './ui/Button';
import {Field,SelectField} from './ui/Field';
export function RecipeEditor({store,onClose}:{store:Nourish;onClose:()=>void}){
  const foods=store.state!.foods.filter(f=>!f.deleted);const [name,setName]=useState('');const [yieldGrams,setYield]=useState(500);const [items,setItems]=useState<{food:Food;grams:number}[]>([]);const [selected,setSelected]=useState(foods[0]?.id??'');const [grams,setGrams]=useState(100);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  return <section className="panel"><h2>A recipe you can come back to</h2><p>Use weighed ingredients, then enter the finished cooked weight. Saved food values are per 100 g.</p><Field label="Recipe name" required value={name} onChange={e=>setName(e.target.value)}/><div className="form-grid"><SelectField label="Ingredient" value={selected} onChange={setSelected}>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</SelectField><Field label="Ingredient grams" type="number" min="1" value={grams} onChange={e=>setGrams(Number(e.target.value))}/></div><Button disabled={!selected||grams<=0} onClick={()=>{const food=foods.find(f=>f.id===selected);if(food)setItems([...items,{food,grams}]);}}>Add ingredient</Button><ul className="recipe-list">{items.map((item,i)=><li key={i}>{item.food.name} · {item.grams} g<Button variant="tertiary" aria-label={`Remove ingredient ${i+1}`} onClick={()=>setItems(items.filter((_,j)=>i!==j))}>Remove</Button></li>)}</ul><Field label="Cooked yield (grams)" type="number" min="1" value={yieldGrams} onChange={e=>setYield(Number(e.target.value))}/>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><Button variant="primary" disabled={busy||!name.trim()||!items.length||yieldGrams<=0} onClick={async()=>{setBusy(true);try{const nutrient=(key:'calories'|'protein'|'fat'|'carbs'|'fiber')=>items.some(i=>i.food[key]==null)?null:items.reduce((s,i)=>s+i.food[key]!*i.grams/100,0)/yieldGrams*100;await store.mutate({kind:'food',recordId:crypto.randomUUID(),expectedRevision:0,delete:false,data:{name,calories:nutrient('calories'),protein:nutrient('protein'),fat:nutrient('fat'),carbs:nutrient('carbs'),fiber:nutrient('fiber'),source:'Personal recipe',servingGrams:100,cookedYieldGrams:yieldGrams,ingredientsJson:JSON.stringify(items),favourite:true}});onClose();}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}}}>Save recipe</Button><Button onClick={onClose}>Cancel</Button></div></section>;
}
