import {useState} from 'react';
import type {Nourish} from '../useNourish';
import type {ScanDraft,AiFood} from '../types';
import {Button} from './ui/Button';
import {Field,SelectField} from './ui/Field';
export function ScanReview({scan,store,date}:{scan:ScanDraft;store:Nourish;date:string}){
  const [foods,setFoods]=useState(scan.result?.foods??[]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const edit=(index:number,key:keyof AiFood,value:unknown)=>setFoods(current=>current.map((f,i)=>i===index?{...f,[key]:value}:f));
  return <section className="panel scan-review"><div className="section-heading"><h2>Review the estimate</h2><Button onClick={()=>void store.removeScan(scan.id)}>Discard draft</Button></div><p className="notice">Editable estimates, not verified measurements.</p>{scan.result!.questions.length>0&&<ul>{scan.result!.questions.map((q,i)=><li key={i}>{q}</li>)}</ul>}
    <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await store.saveReviewedScan(scan.id,foods.map(food=>({...food,date,meal:'Meal',source:scan.mode==='label'?'AI label · reviewed':'AI estimate · reviewed'})));}catch(ex){setError((ex as Error).message);}finally{setBusy(false);}}}>
    {foods.map((food,i)=><fieldset key={i}><legend>Food {i+1}</legend><Field label="Name" required value={food.name} onChange={e=>edit(i,'name',e.target.value)}/><p>{food.notes}</p><div className="form-grid"><SelectField label="Quantity unit" value={food.unit} onChange={v=>edit(i,'unit',v)}><option value="g">Grams</option><option value="serving">Servings</option></SelectField><Field label={`Quantity (${food.unit})`} type="number" min="0.001" required step="any" value={food.quantity} onChange={e=>edit(i,'quantity',Number(e.target.value))}/><Field label="Calories for this quantity" type="number" min="0" max="20000" required step="any" value={food.calories} onChange={e=>edit(i,'calories',Number(e.target.value))}/>{(['protein','carbs','fat','fiber'] as const).map(key=><Field key={key} label={`${key} (g)`} type="number" min="0" max="3000" step="any" value={food[key]??''} placeholder="Unknown" onChange={e=>edit(i,key,e.target.value===''?null:Number(e.target.value))}/>)}</div><Button variant="tertiary" onClick={()=>setFoods(foods.filter((_,j)=>j!==i))}>Remove this food</Button></fieldset>)}{error&&<p className="error" role="alert">{error}</p>}<Button variant="primary" type="submit" disabled={!foods.length||busy}>{busy?'Saving…':`Add reviewed meal to ${date}`}</Button></form></section>;
}
